### ISSUE TITLE
Add simple Interface

### ISSUE THREAD

**Issue by pknoe3lh** [pknoe3lh/cncgcodecontroller#14]
And may be you deal a standart circle on interface like a prontoface aka repetier host for moving cnc. and options for moving cnc via keypad.

**Comment by Nutz95** [comment]
I've created a pull request to add this functionality as it bothered me for quite some time now.

**Comment by Nutz95** [comment]
fixed on PR https://github.com/pknoe3lh/cncgcodecontroller/commit/6018c81f5da4e045df3ca587e1cd8abfd9aa948d i think we can close this item

**Comment by pknoe3lh** [comment]
added in 5.0

**Comment by zhongstudio** [comment]
good upgrade.
I'm trying.
thank you.
----- 原始邮件 -----
发件人：pknoe3lh <notifications@github.com>
收件人：pknoe3lh/cncgcodecontroller <cncgcodecontroller@noreply.github.com>
主题：Re: [cncgcodecontroller] Add simple Interface (#14)
日期：2015年04月04日 03点50分

Closed #14.

&mdash;
