### ISSUE TITLE
Add separate "Home Z axis" option

### ISSUE THREAD

**Issue by carlosgs** [pknoe3lh/cncgcodecontroller#18]
Hi, I have been using CncGcodeController for a while now (very convenient software, thanks!) and I am missing separate homing options.
In my current setup, when pressing "Homing" thr XY axes travel to zero and then Z goes down until I manually make contact with the probe wires. How does this differ from your Marlin configuration? 

I wanted to ask for a new feature, to split the homing button into "Home XY" and "Home Z". That way it would be possible to zero the height in a more controlled manner without having to manually stop Z homing and later type G28 Z0 in the console.

**Comment by Nutz95** [comment]
A pull request is in the queue right now with a simple pronter face like user interface that allows nearly the same things as pronterface except the mangement of heating elements of course.
So home separately X, Y and Z is possible as well as XY and XYZ at once.

**Comment by Nutz95** [comment]
managed by PR https://github.com/pknoe3lh/cncgcodecontroller/commit/6018c81f5da4e045df3ca587e1cd8abfd9aa948d we may close this item

**Comment by pknoe3lh** [comment]
added in 5.0
