### ISSUE TITLE
Workflow Issue

### ISSUE THREAD

**Issue by hokum86** [pknoe3lh/cncgcodecontroller#23]
Hi,

i'm a bit new to this toppic and I have a question.

I'm a proud owner of a millig machin and would like to use this programm to control my machine. 
I wanted to mill a block from wood to test its capabilities and I ran into a problem.

I don't kow how to set the Z Zeropoint from my material.

So my question is, how are you doing it?
Do you move the mill towards the material and when the tool hits the surface you use Set Position?

It would be great if you can help me. 

Heiko.

**Comment by pknoe3lh** [comment]
Hello Heiko,

You can use set position under advanced Controls.

The software originates from the desire to use Marlin (or other Firmwares) to control a CNC Machines. In Marlin there is no possibility to set the Material zeroposition. The idea of this software is to reduce the problems of using CNC G-Code for Marlin. (Marlin does not support a lot of common G Codes)

I wrote the software exactly for that problem. I mainly use it now for Prototyping of circuit boards. 
The circuit boards are conductive so i use the "Auto level" option. Therefor i get the exact height of the board. 

If you have ideas how to make the software better feel free to contribute. I have limited time now so i cannot implement it. But if you submit code i will add it to the project. 

greetings 
Patrick
