### ISSUE TITLE
Autolevel problem

### ISSUE THREAD

**Issue by Dreyer1416** [pknoe3lh/cncgcodecontroller#25]
#How exactly the autolevel works? 

I am using the latest Marlin version and a Zmin endstop but its doesn't detect the endstop trigger

Thanks

Edit: I figure it out. Apparently I commented out #define ENDSTOPS_ONLY_FOR_HOMING in the configuration_adv.h file

**Comment by pknoe3lh** [comment]
Hello,

perfect,
